version: 2.1

orbs:
  orb-tools: circleci/orb-tools@2.0.0

workflows:
  publish_deploy_to_aws_with_terragrunt_orb:
    jobs:
    - orb-tools/publish:
        orb-path: source/deploy_to_aws_with_terragrunt/orb.yml
        orb-ref: moonpig-sandbox/deploy_to_aws_with_terragrunt@1.0.${CIRCLE_BUILD_NUM}
        publish-token-variable: ${CIRCLECI_API_TOKEN}
        validate: true
